# Generated by Django 2.1.5 on 2019-03-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iso',
            old_name='iso',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='states',
            old_name='states',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='site',
            name='area_hectare',
            field=models.FloatField(null=True),
        ),
    ]
